spring.application.name=cyan
server.port=${PORT:8081}
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://hoangthe8944_db_user:chCDWnZpBxygIjsx@cluster0.psdthsd.mongodb.net/cyan?retryWrites=true&w=majority}
spring.data.mongodb.auto-index-creation=true
spring.jackson.default-property-inclusion=non_null
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
logging.level.org.springframework.web=DEBUG

app.upload-dir=${APP_UPLOAD_DIR:./uploads}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.image-folder=${CLOUDINARY_IMAGE_FOLDER:products/images}
cloudinary.video-folder=${CLOUDINARY_VIDEO_FOLDER:banners/videos}

momo.enabled=${MOMO_ENABLED:false}
momo.endpoint=${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
momo.partner-code=${MOMOLRJZ20181206:}
momo.access-key=${mTCKt9W3eU1m39TW:}
momo.secret-key=${SetA5RDnLHvt51AULf51DyauxUo3kDU6:}
momo.redirect-url=${MOMO_REDIRECT_URL:}
momo.ipn-url=${MOMO_IPN_URL:}
momo.order-type=${MOMO_ORDER_TYPE:momo_wallet}
momo.request-type=${MOMO_REQUEST_TYPE:CAPTURE_WALLET}
momo.lang=${MOMO_LANG:vi}
